### ISSUE TITLE
Wrap section headings in an anchor so that they are easily linkable

### ISSUE THREAD

**Issue by jseppi** [18F/federalist-report-template#18]
Would be nice if the section headers were wrapped with an anchor that looked like `<a href="#section-heading-slug">` to make it a little easier to click on a heading and then share the url to that specific section.

**Comment by line47** [comment]
Which headings are you referring to here @jseppi ?

**Comment by jseppi** [comment]
all of them, basically. Like `I. Ipsum` and `II. Morem Ipsum` in this screenshot:

<img width="729" alt="screen shot 2018-01-02 at 9 06 45 am" src="https://user-images.githubusercontent.com/697848/34487997-49d49158-ef9c-11e7-825d-1c6798bb3353.png">

**Comment by wslack** [comment]
Agreed this is a best practice; not sure how it fits in @line47's plans. Won't triage for now.

**Comment by line47** [comment]
This functionality got merged into uswds-jekyll https://github.com/18F/uswds-jekyll/pull/45 after releasing a new version of uswds-jekyll, I'd like to update https://github.com/18F/federalist-uswds-template/

**Comment by wslack** [comment]
Can we update our template now?

**Comment by line47** [comment]
I need to publish the update for uswds-jekyll first to https://rubygems.org/gems/uswds-jekyll

**Comment by wslack** [comment]
@line47 can this be included within your existing template work?

**Comment by line47** [comment]
This is already baked in to uswds-jekyll and federalist-uswds-template by way of Kramdown which is the default Jekyll markdown processor. This functionality will be rolled into the other templates as they are updated.

So yeah, it's already rolled in (progress)

**Comment by wslack** [comment]
cool. Let's plan to close this when the new report template is live?

**Comment by line47** [comment]
I'd also add the one page template to that

**Comment by wslack** [comment]
👍
