### ISSUE TITLE
Add documentation for how to run this locally

### ISSUE THREAD

**Issue by maya** [18F/federalist-report-template#22]
Also, how do I get it to watch Sass? I tried making a change to `assets/sass/main.scss` but it's not updating. I did `jekyll serve` to run it.

**Comment by wslack** [comment]
@maya I'm confused. You mean building it locally with Jekyll?

**Comment by line47** [comment]
Take a look here @maya https://github.com/18F/uswds-jekyll#installation this template will soon be built off of this uswds-jekyll theme
